"""Schemas para validação e serialização de dados.

Este módulo organiza todos os schemas Pydantic usados para
validação de entrada, serialização de saída e documentação da API."""

# Schemas base
from app.schemas.base import (
    BaseEntitySchema,
    BaseSchema,
    BulkOperationRequest,
    BulkOperationResponse,
    ErrorDetail,
    ErrorResponse,
    FilterParams,
    HealthCheckResponse,
    MetricsResponse,
    PaginatedResponse,
    PaginationParams,
    SortParams,
    SuccessResponse,
    TimestampSchema,
    UUIDSchema,
)

# Schemas de usuário
from app.schemas.user import (
    EmailVerification,
    PasswordChange,
    PasswordReset,
    PasswordResetConfirm,
    TokenResponse,
    UserBase,
    UserCreate,
    UserLogin,
    UserPreferencesBase,
    UserPreferencesResponse,
    UserPreferencesUpdate,
    UserResponse,
    UserStatsResponse,
    UserUpdate,
)

# Schemas de autenticação
from app.schemas.auth import (
    PasswordChange as AuthPasswordChange,
    PasswordReset as AuthPasswordReset,
    PasswordResetRequest,
    Token,
    TokenData,
    UserLogin as AuthUserLogin,
    UserRegister,
)

# Schemas de sistema
from app.schemas.system import (
    SystemBase,
    SystemCreate,
    SystemEmulatorBase,
    SystemEmulatorCreate,
    SystemEmulatorResponse,
    SystemEmulatorUpdate,
    SystemFilterParams,
    SystemMetadataBase,
    SystemMetadataCreate,
    SystemMetadataResponse,
    SystemMetadataUpdate,
    SystemResponse,
    SystemSearchRequest,
    SystemStatsResponse,
    SystemUpdate,
)

# Schemas de jogos
from app.schemas.game import (
    GameBase,
    GameCreate,
    GameFilterParams,
    GameGenreBase,
    GameGenreCreate,
    GameGenreResponse,
    GameGenreUpdate,
    GameMetadataBase,
    GameMetadataCreate,
    GameMetadataResponse,
    GameMetadataUpdate,
    GamePlayUpdate,
    GameResponse,
    GameScreenshotBase,
    GameScreenshotCreate,
    GameScreenshotResponse,
    GameScreenshotUpdate,
    GameSearchRequest,
    GameSearchResponse,
    GameStatsResponse,
    GameUpdate,
)

# Schemas de ROMs
from app.schemas.rom import (
    CompressionType,
    ROMBase,
    ROMBulkOperation,
    ROMCreate,
    ROMFileBase,
    ROMFileCreate,
    ROMFileResponse,
    ROMFileUpdate,
    ROMFilterParams,
    ROMHashUpdate,
    ROMImportRequest,
    ROMResponse,
    ROMSearchRequest,
    ROMStatsResponse,
    ROMStatus,
    ROMUpdate,
    ROMVerificationBase,
    ROMVerificationCreate,
    ROMVerificationResponse,
    ROMVerifyRequest,
    VerificationSource,
    VerificationType,
)

# Schemas de tarefas
from app.schemas.task import (
    TaskBase,
    TaskBulkOperation,
    TaskCancelRequest,
    TaskCreate,
    TaskFilterParams,
    TaskPriority,
    TaskProgressUpdate,
    TaskQueueInfo,
    TaskResponse,
    TaskResultBase,
    TaskResultCreate,
    TaskResultResponse,
    TaskResultType,
    TaskResultUpdate,
    TaskRetryRequest,
    TaskSearchRequest,
    TaskStatsResponse,
    TaskStatus,
    TaskSystemStatus,
    TaskType,
    TaskUpdate,
)

__all__ = [
    # Base
    "BaseSchema",
    "BaseEntitySchema",
    "TimestampSchema",
    "UUIDSchema",
    "PaginationParams",
    "SortParams",
    "FilterParams",
    "PaginatedResponse",
    "ErrorDetail",
    "ErrorResponse",
    "SuccessResponse",
    "HealthCheckResponse",
    "MetricsResponse",
    "BulkOperationRequest",
    "BulkOperationResponse",
    # User
    "UserBase",
    "UserCreate",
    "UserUpdate",
    "UserResponse",
    "UserLogin",
    "TokenResponse",
    "PasswordChange",
    "PasswordReset",
    "PasswordResetConfirm",
    "EmailVerification",
    "UserPreferencesBase",
    "UserPreferencesUpdate",
    "UserPreferencesResponse",
    "UserStatsResponse",
    # Auth
    "Token",
    "TokenData",
    "AuthUserLogin",
    "UserRegister",
    "PasswordResetRequest",
    "AuthPasswordReset",
    "AuthPasswordChange",
    # System
    "SystemBase",
    "SystemCreate",
    "SystemUpdate",
    "SystemResponse",
    "SystemEmulatorBase",
    "SystemEmulatorCreate",
    "SystemEmulatorUpdate",
    "SystemEmulatorResponse",
    "SystemMetadataBase",
    "SystemMetadataCreate",
    "SystemMetadataUpdate",
    "SystemMetadataResponse",
    "SystemFilterParams",
    "SystemSearchRequest",
    "SystemStatsResponse",
    # Game
    "GameBase",
    "GameCreate",
    "GameUpdate",
    "GameResponse",
    "GameGenreBase",
    "GameGenreCreate",
    "GameGenreUpdate",
    "GameGenreResponse",
    "GameScreenshotBase",
    "GameScreenshotCreate",
    "GameScreenshotUpdate",
    "GameScreenshotResponse",
    "GameMetadataBase",
    "GameMetadataCreate",
    "GameMetadataUpdate",
    "GameMetadataResponse",
    "GameFilterParams",
    "GameSearchRequest",
    "GameSearchResponse",
    "GameStatsResponse",
    "GamePlayUpdate",
    # ROM
    "ROMBase",
    "ROMCreate",
    "ROMUpdate",
    "ROMResponse",
    "ROMStatus",
    "CompressionType",
    "ROMFileBase",
    "ROMFileCreate",
    "ROMFileUpdate",
    "ROMFileResponse",
    "ROMVerificationBase",
    "ROMVerificationCreate",
    "ROMVerificationResponse",
    "VerificationType",
    "VerificationSource",
    "ROMFilterParams",
    "ROMSearchRequest",
    "ROMStatsResponse",
    "ROMHashUpdate",
    "ROMVerifyRequest",
    "ROMBulkOperation",
    "ROMImportRequest",
    # Task
    "TaskBase",
    "TaskCreate",
    "TaskUpdate",
    "TaskResponse",
    "TaskStatus",
    "TaskPriority",
    "TaskType",
    "TaskResultBase",
    "TaskResultCreate",
    "TaskResultUpdate",
    "TaskResultResponse",
    "TaskResultType",
    "TaskFilterParams",
    "TaskSearchRequest",
    "TaskStatsResponse",
    "TaskProgressUpdate",
    "TaskRetryRequest",
    "TaskCancelRequest",
    "TaskBulkOperation",
    "TaskQueueInfo",
    "TaskSystemStatus",
]